GET http://localhost:8000/api/v1/movies

###

GET http://localhost:8000/api/v1/movies/[id]

###

POST http://localhost:8000/api/v1/movies
Content-Type: application/json

{
    "title": "Thor: Love Or Thunder",
    "director": "Taika Waititi",
    "releaseYear": 2022
}

###

PATCH http://localhost:8000/api/v1/movies/[id]
Content-Type: application/json

{
    "title":"Thor: Love Is Thunder",
    "director":"Taika Waitit",
    "releaseYear":"2022" 
}

###

DELETE http://localhost:8000/api/v1/movies/[id]